// End-to-end upload validation by driving the REAL UI with Chromium.
// Works against the local mock server and against production (where the
// real Turnstile widget executes inside the page, so no token forgery).
//
// Ground truth per case: the intercepted /api/chat POST must carry the
// expected number of attachments, and the assistant must stream a reply.
//
// Usage: node validate-live.mjs [baseUrl]
//   default baseUrl: http://localhost:3000
//
// All test documents are SYNTHETIC (generated by gen-assets.mjs).
import { chromium } from "playwright-core";
import path from "node:path";
import fs from "node:fs";

const BASE = (process.argv[2] ?? "http://localhost:3000").replace(/\/$/, "");
const ASSETS = new URL("./assets/", import.meta.url).pathname;
const SHOTS = new URL("./shots/", import.meta.url).pathname;
fs.mkdirSync(SHOTS, { recursive: true });

const a = (f) => path.join(ASSETS, f);

const CASES = [
  {
    name: "jpeg-single",
    files: [a("letter-page-1.jpg")],
    text: "What is this letter asking me to do, and by when?",
  },
  {
    name: "png-single",
    files: [a("letter-page-3.png")],
    text: "What rights does this page say I have?",
  },
  {
    name: "multi-image-4",
    files: [1, 2, 3, 4].map((n) => a(`letter-page-${n}.jpg`)),
    text: "These four photos are one letter. What do I need to send and where?",
  },
  {
    name: "pdf-multipage",
    files: [a("letter-4pages.pdf")],
    expectTypes: ["application/pdf"],
    text: "Please summarize this PDF for me in plain words.",
  },
  {
    name: "image-only-no-text",
    files: [a("letter-page-2.jpg")],
    text: "", // image-only send: no typed message
  },
];

const browser = await chromium.launch({
  executablePath: process.env.CHROME_PATH ?? "/opt/pw-browsers/chromium",
  headless: process.env.HEADED !== "1",
});

const results = [];

for (const tc of CASES) {
  const context = await browser.newContext({
    viewport: { width: 390, height: 844 }, // iPhone-ish; mobile is the product
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  });
  const page = await context.newPage();
  const started = Date.now();
  let outcome = { name: tc.name, ok: false };
  const posts = [];

  page.on("request", (req) => {
    if (req.url().includes("/api/chat") && req.method() === "POST") {
      try {
        const parsed = JSON.parse(req.postData() ?? "");
        const last = parsed.messages.at(-1);
        posts.push({
          bodyBytes: (req.postData() ?? "").length,
          attachments: (last.attachments ?? []).map((x) => ({
            mediaType: x.mediaType,
            base64Length: x.dataBase64.length,
          })),
        });
      } catch {
        posts.push({ parseFailed: true });
      }
    }
  });

  try {
    await page.goto(`${BASE}/conversation/understand-letter-or-form`, {
      waitUntil: "load",
      timeout: 90_000, // first hit on a cold dev server compiles the page
    });
    const composer = page.locator("#conversation-input");
    await composer.waitFor({ state: "visible", timeout: 30_000 });

    // Attach through the hidden multi-file picker (same code path as the
    // paperclip button) so downscale/EXIF-strip/preview logic runs for
    // real. React may still be hydrating when the input first appears, so
    // retry the pick until the send button enables (it enables on pending
    // attachments even with an empty draft).
    const picker = page.locator('input[type="file"][multiple]');
    const sendButton = page.locator('form button[type="submit"]');
    let attached = false;
    for (let attempt = 0; attempt < 5 && !attached; attempt += 1) {
      await page.waitForTimeout(attempt === 0 ? 1500 : 2000);
      await picker.setInputFiles(tc.files);
      attached = await sendButton
        .waitFor({ state: "visible", timeout: 1_000 })
        .then(() =>
          page.waitForFunction(
            () =>
              !document
                .querySelector('form button[type="submit"]')
                ?.hasAttribute("disabled"),
            null,
            { timeout: 10_000 },
          ),
        )
        .then(() => true)
        .catch(() => false);
    }
    if (!attached) throw new Error("attachment never enabled the send button");

    if (tc.text) await composer.fill(tc.text);
    const sendAt = Date.now();
    await sendButton.click();

    // Streaming is done when aria-busy flips back to false and the thread
    // has grown past the user's own bubble.
    await page.waitForFunction(
      () =>
        document
          .querySelector("section[aria-live]")
          ?.getAttribute("aria-busy") === "false" &&
        (document.querySelector("section[aria-live]")?.textContent?.length ??
          0) > 80,
      null,
      { timeout: 180_000 },
    );

    const thread = await page
      .locator("section[aria-live]")
      .innerText({ timeout: 5_000 });
    const streamMs = Date.now() - sendAt;

    const post = posts.find((p) => (p.attachments?.length ?? 0) > 0);
    const wireOk =
      post &&
      post.attachments.length === tc.files.length &&
      (tc.expectTypes
        ? tc.expectTypes.every((t, i) => post.attachments[i]?.mediaType === t)
        : post.attachments.every((x) => x.mediaType === "image/jpeg"));

    const replyOk =
      thread.length > 120 &&
      !/something went wrong|try again in a moment/i.test(thread);

    await page.screenshot({
      path: path.join(SHOTS, `${tc.name}.png`),
      fullPage: true,
    });

    outcome = {
      name: tc.name,
      ok: Boolean(wireOk && replyOk),
      wireOk: Boolean(wireOk),
      replyOk,
      post,
      streamMs,
      totalMs: Date.now() - started,
      threadChars: thread.length,
      threadTail: thread.slice(-200).replace(/\s+/g, " "),
    };
  } catch (error) {
    outcome.error = String(error).slice(0, 300);
    outcome.post = posts[0];
    await page
      .screenshot({ path: path.join(SHOTS, `${tc.name}-FAIL.png`), fullPage: true })
      .catch(() => {});
  }

  results.push(outcome);
  console.log(
    `${outcome.ok ? "PASS" : "FAIL"} ${tc.name}` +
      (outcome.post?.attachments
        ? ` [wire: ${outcome.post.attachments
            .map((x) => `${x.mediaType} ${Math.round(x.base64Length / 1024)}KB`)
            .join(", ")} | body ${Math.round((outcome.post.bodyBytes ?? 0) / 1024)}KB]`
        : "") +
      (outcome.streamMs ? ` (stream ${outcome.streamMs}ms)` : "") +
      (outcome.error ? ` — ${outcome.error}` : ""),
  );
  await context.close();
}

await browser.close();

const passed = results.filter((r) => r.ok).length;
console.log(`\n${passed}/${results.length} cases passed against ${BASE}`);
fs.writeFileSync(
  new URL("./validate-results.json", import.meta.url).pathname,
  JSON.stringify(results, null, 2),
);
process.exit(passed === results.length ? 0 : 1);
